language: java
sudo: false
install: true
dist: trusty
jdk:
  - oraclejdk8
os:
  - linux
branches:
  only:
  -master
  -develop
notifications:
  email:
    recipients:
    - kashenkovsergej@yandex.ru
    on_success: always
    on_failure: always
